version: '2'
services:
  app:
    container_name: easy-homeworks-front-staging
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    ports:
      - ${GATEWAY_PORT}:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment: 
      - REACT_APP_SERVER_URL="https://easyhomeworks.wns.wilders.dev/graphql/"
