version: '2'
services:
  app:
    container_name: easy-homeworks-front-dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - ${GATEWAY_PORT}:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment: 
      - REACT_APP_SERVER_URL="http://localhost:8080/graphql/"
